# Generated by Django 5.2.10 on 2026-01-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('H', '高'), ('M', '中'), ('L', '低')], default='M', max_length=1),
        ),
    ]
